  react: 
    build: .
    dockerfile: Dockerfile
    container_name: reactApp
    ports:
      - 4000:4000
    links:
      - database
      
  database:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ~/mongo:/data/db